In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
path = r"C:\Users\ramaw\Downloads\drugs classification/drug200.csv"
data = pd.read_csv(path)
print(data)

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]


In [4]:
x = data.iloc[:, [0,2,3,4]].values
y = data.iloc[:, -1].values

In [5]:
print(x)

[[23 'HIGH' 'HIGH' 25.355]
 [47 'LOW' 'HIGH' 13.093]
 [47 'LOW' 'HIGH' 10.114]
 [28 'NORMAL' 'HIGH' 7.798]
 [61 'LOW' 'HIGH' 18.043]
 [22 'NORMAL' 'HIGH' 8.607]
 [49 'NORMAL' 'HIGH' 16.275]
 [41 'LOW' 'HIGH' 11.037]
 [60 'NORMAL' 'HIGH' 15.171]
 [43 'LOW' 'NORMAL' 19.368]
 [47 'LOW' 'HIGH' 11.767]
 [34 'HIGH' 'NORMAL' 19.199]
 [43 'LOW' 'HIGH' 15.376]
 [74 'LOW' 'HIGH' 20.942]
 [50 'NORMAL' 'HIGH' 12.703]
 [16 'HIGH' 'NORMAL' 15.516]
 [69 'LOW' 'NORMAL' 11.455]
 [43 'HIGH' 'HIGH' 13.972]
 [23 'LOW' 'HIGH' 7.298]
 [32 'HIGH' 'NORMAL' 25.974]
 [57 'LOW' 'NORMAL' 19.128]
 [63 'NORMAL' 'HIGH' 25.917]
 [47 'LOW' 'NORMAL' 30.568]
 [48 'LOW' 'HIGH' 15.036]
 [33 'LOW' 'HIGH' 33.486]
 [28 'HIGH' 'NORMAL' 18.809]
 [31 'HIGH' 'HIGH' 30.366]
 [49 'NORMAL' 'NORMAL' 9.381]
 [39 'LOW' 'NORMAL' 22.697]
 [45 'LOW' 'HIGH' 17.951]
 [18 'NORMAL' 'NORMAL' 8.75]
 [74 'HIGH' 'HIGH' 9.567]
 [49 'LOW' 'NORMAL' 11.014]
 [65 'HIGH' 'NORMAL' 31.876]
 [53 'NORMAL' 'HIGH' 14.133]
 [46 'NORMAL' 'NORMAL' 7.285]
 [32 

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(), [1, 2]),
    ('passthrough', 'passthrough', [0,3])
], remainder='drop')
x = np.array(ct.fit_transform(x))

In [7]:
print(x)

[[1.0 0.0 0.0 ... 0.0 23 25.355]
 [0.0 1.0 0.0 ... 0.0 47 13.093]
 [0.0 1.0 0.0 ... 0.0 47 10.114]
 ...
 [0.0 0.0 1.0 ... 0.0 52 9.894]
 [0.0 0.0 1.0 ... 1.0 23 14.02]
 [0.0 1.0 0.0 ... 1.0 40 11.349]]


In [8]:
print(y)

['DrugY' 'drugC' 'drugC' 'drugX' 'DrugY' 'drugX' 'DrugY' 'drugC' 'DrugY'
 'DrugY' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'drugX' 'drugA'
 'drugC' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'drugX' 'drugB' 'drugX' 'DrugY' 'drugX' 'drugX'
 'drugA' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugB' 'DrugY' 'drugX' 'drugX'
 'drugX' 'drugA' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY'
 'drugB' 'drugC' 'drugB' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'drugA' 'DrugY'
 'drugX' 'drugB' 'DrugY' 'drugA' 'drugX' 'DrugY' 'DrugY' 'drugB' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'DrugY' 'drugA' 'DrugY' 'drugA' 'drugX' 'drugB'
 'drugX' 'drugC' 'drugA' 'drugC' 'drugB' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'drugA' 'drugA' 'drugC' 'drugX' 'DrugY' 'drugX' 'drugX' 'DrugY'
 'drugB' 'DrugY' 'drugA' 'drugX' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugX'
 'drugX' 'drugA' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'D

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 3 3 4 0 4 0 3 0 0 3 0 0 0 4 0 4 1 3 0 0 0 0 0 0 0 0 4 0 0 4 2 4 0 4 4 1
 4 4 4 0 2 0 4 4 4 1 3 0 0 0 4 0 0 2 3 2 0 4 0 0 1 0 4 2 0 1 4 0 0 2 0 4 0
 0 0 1 0 1 4 2 4 3 1 3 2 4 0 0 0 0 0 0 0 0 4 0 0 0 0 1 1 3 4 0 4 4 0 2 0 1
 4 4 4 4 0 4 4 1 0 0 0 0 0 2 0 0 4 0 4 0 0 4 0 0 4 2 1 2 4 1 0 2 0 1 4 4 1
 4 3 1 2 4 4 0 3 1 0 3 4 4 2 4 0 0 0 0 4 0 1 4 4 0 0 1 0 1 0 0 0 0 4 4 0 0
 0 2 1 0 0 0 1 0 3 0 3 3 4 4 4]


In [11]:
# 0 = drugY
# 1 = drugA
# 2 = drugB
# 3 = drugC
# 4 = drugX

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [13]:
print(x_train)

[[0.0 0.0 1.0 ... 0.0 28 19.675]
 [1.0 0.0 0.0 ... 1.0 53 12.495]
 [1.0 0.0 0.0 ... 0.0 18 37.188]
 ...
 [0.0 0.0 1.0 ... 0.0 40 10.103]
 [0.0 1.0 0.0 ... 0.0 68 10.291]
 [0.0 0.0 1.0 ... 1.0 39 17.225]]


In [14]:
print(x_test)

[[0.0 1.0 0.0 1.0 0.0 23 7.298]
 [0.0 0.0 1.0 1.0 0.0 28 12.879]
 [0.0 1.0 0.0 1.0 0.0 42 20.013]
 [1.0 0.0 0.0 0.0 1.0 20 35.639]
 [0.0 0.0 1.0 1.0 0.0 25 19.011]
 [0.0 1.0 0.0 0.0 1.0 20 11.686]
 [0.0 0.0 1.0 1.0 0.0 22 8.607]
 [0.0 1.0 0.0 0.0 1.0 37 12.006]
 [0.0 1.0 0.0 1.0 0.0 43 15.376]
 [0.0 0.0 1.0 0.0 1.0 55 7.261]
 [1.0 0.0 0.0 0.0 1.0 24 9.475]
 [1.0 0.0 0.0 0.0 1.0 19 25.969]
 [1.0 0.0 0.0 0.0 1.0 22 22.818]
 [0.0 1.0 0.0 0.0 1.0 37 16.724]
 [1.0 0.0 0.0 1.0 0.0 60 13.934]
 [0.0 1.0 0.0 1.0 0.0 41 11.037]
 [1.0 0.0 0.0 0.0 1.0 65 31.876]
 [0.0 0.0 1.0 1.0 0.0 70 20.489]
 [0.0 1.0 0.0 0.0 1.0 39 13.938]
 [1.0 0.0 0.0 0.0 1.0 31 17.069]
 [1.0 0.0 0.0 0.0 1.0 36 15.49]
 [0.0 0.0 1.0 1.0 0.0 61 9.443]
 [0.0 0.0 1.0 0.0 1.0 66 8.107]
 [0.0 1.0 0.0 0.0 1.0 34 12.923]
 [0.0 1.0 0.0 0.0 1.0 38 29.875]
 [0.0 0.0 1.0 1.0 0.0 36 16.753]
 [0.0 0.0 1.0 1.0 0.0 67 15.891]
 [0.0 0.0 1.0 0.0 1.0 57 25.893]
 [0.0 0.0 1.0 1.0 0.0 34 22.456]
 [0.0 0.0 1.0 0.0 1.0 50 12.295]
 [0.0 1.0 0.0 0.0

In [15]:
print(y_train)

[0 2 0 0 3 0 4 4 0 2 0 0 4 0 4 0 2 0 4 4 4 0 1 1 1 0 0 4 4 0 1 1 2 3 2 0 3
 0 2 4 4 3 0 0 3 0 0 0 0 4 3 1 0 0 0 1 4 2 4 2 0 0 0 2 0 2 0 2 4 0 0 1 0 0
 1 1 4 4 0 4 0 0 3 0 3 4 1 0 4 0 0 3 4 0 0 3 0 4 0 4 4 0 1 4 0 0 0 0 4 0 4
 2 2 0 4 1 4 2 1 1 0 0 3 4 0 4 3 4 0 0 0 4 0 1 0 4 4 1 0 2 0 1 0 0 4 4 0 4
 3 0]


In [16]:
print(y_test)

[3 4 0 0 0 4 4 4 0 4 1 0 0 0 2 3 0 0 4 0 0 4 4 4 0 0 0 0 0 4 4 3 1 4 0 0 4
 0 1 4 0 1 0 4 0 4 0 0 1 0]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 6:] = sc.fit_transform(x_train[:, 6:])
x_test[:, 6:] = sc.transform(x_test[:, 6:])

In [18]:
print(x_train)

[[0.0 0.0 1.0 ... 0.0 28 0.5063401903884647]
 [1.0 0.0 0.0 ... 1.0 53 -0.4868109837351762]
 [1.0 0.0 0.0 ... 0.0 18 2.9287714595287597]
 ...
 [0.0 0.0 1.0 ... 0.0 40 -0.8176769459223276]
 [0.0 1.0 0.0 ... 0.0 68 -0.7916724304995916]
 [0.0 0.0 1.0 ... 1.0 39 0.16745155854961802]]


In [19]:
print(x_test)

[[0.0 1.0 0.0 1.0 0.0 23 -1.2056698489051705]
 [0.0 0.0 1.0 1.0 0.0 28 -0.4336953777653324]
 [0.0 1.0 0.0 1.0 0.0 42 0.553092989393171]
 [1.0 0.0 0.0 0.0 1.0 20 2.714510851072281]
 [0.0 0.0 1.0 1.0 0.0 25 0.41449445506560967]
 [0.0 1.0 0.0 0.0 1.0 20 -0.5987133931872687]
 [0.0 0.0 1.0 1.0 0.0 22 -1.0246064941798438]
 [0.0 1.0 0.0 0.0 1.0 37 -0.5544503882123989]
 [0.0 1.0 0.0 1.0 0.0 43 -0.08830561707080167]
 [0.0 0.0 1.0 0.0 1.0 55 -1.21078775885539]
 [1.0 0.0 0.0 0.0 1.0 24 -0.9045430931855096]
 [1.0 0.0 0.0 0.0 1.0 19 1.3769381694879346]
 [1.0 0.0 0.0 0.0 1.0 22 0.9410858923760138]
 [0.0 1.0 0.0 0.0 1.0 37 0.09815229138583736]
 [1.0 0.0 0.0 1.0 0.0 60 -0.28776578323880864]
 [0.0 1.0 0.0 1.0 0.0 41 -0.6884843001519263]
 [1.0 0.0 0.0 0.0 1.0 65 2.1940055769459215]
 [0.0 0.0 1.0 1.0 0.0 70 0.6189342092932897]
 [0.0 1.0 0.0 0.0 1.0 39 -0.28721249567662255]
 [1.0 0.0 0.0 0.0 1.0 31 0.14587334362436868]
 [1.0 0.0 0.0 0.0 1.0 36 -0.0725369215485042]
 [0.0 0.0 1.0 1.0 0.0 61 -0.9089693936829

In [20]:
x_train[:, 5:6] = sc.fit_transform(x_train[:, 5:6])
x_test[:, 5:6] = sc.transform(x_test[:, 5:6])

In [21]:
print(x_test)

[[0.0 1.0 0.0 1.0 0.0 -1.3213782877828895 -1.2056698489051705]
 [0.0 0.0 1.0 1.0 0.0 -1.0211560170051956 -0.4336953777653324]
 [0.0 1.0 0.0 1.0 0.0 -0.1805336588276532 0.553092989393171]
 [1.0 0.0 0.0 0.0 1.0 -1.5015116502495056 2.714510851072281]
 [0.0 0.0 1.0 1.0 0.0 -1.2012893794718118 0.41449445506560967]
 [0.0 1.0 0.0 0.0 1.0 -1.5015116502495056 -0.5987133931872687]
 [0.0 0.0 1.0 1.0 0.0 -1.3814227419384282 -1.0246064941798438]
 [0.0 1.0 0.0 0.0 1.0 -0.48075592960534697 -0.5544503882123989]
 [0.0 1.0 0.0 1.0 0.0 -0.12048920467211448 -0.08830561707080167]
 [0.0 0.0 1.0 0.0 1.0 0.6000442451943505 -1.21078775885539]
 [1.0 0.0 0.0 0.0 1.0 -1.2613338336273507 -0.9045430931855096]
 [1.0 0.0 0.0 0.0 1.0 -1.5615561044050443 1.3769381694879346]
 [1.0 0.0 0.0 0.0 1.0 -1.3814227419384282 0.9410858923760138]
 [0.0 1.0 0.0 0.0 1.0 -0.48075592960534697 0.09815229138583736]
 [1.0 0.0 0.0 1.0 0.0 0.9002665159720442 -0.28776578323880864]
 [0.0 1.0 0.0 1.0 0.0 -0.24057811298319196 -0.68848430015192

In [22]:
print(x_train)

[[0.0 0.0 1.0 ... 0.0 -1.0211560170051956 0.5063401903884647]
 [1.0 0.0 0.0 ... 1.0 0.47995533688327296 -0.4868109837351762]
 [1.0 0.0 0.0 ... 0.0 -1.621600558560583 2.9287714595287597]
 ...
 [0.0 0.0 1.0 ... 0.0 -0.3006225671387307 -0.8176769459223276]
 [0.0 1.0 0.0 ... 0.0 1.3806221492163542 -0.7916724304995916]
 [0.0 0.0 1.0 ... 1.0 -0.3606670212942695 0.16745155854961802]]


In [23]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [24]:
y_pred = classifier.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 9  5  2  3  6]
 [ 0  5  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0 16]]


In [45]:
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  0.68


In [26]:
from sklearn.linear_model import LogisticRegression

classifierr = LogisticRegression()
classifierr.fit(x_train, y_train)

LogisticRegression()

In [27]:
y_predd = classifier.predict(x_test)

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predd)
print(cm)

[[ 9  5  2  3  6]
 [ 0  5  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0 16]]


In [44]:
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_test, y_predd))

Accuracy:  0.68


In [29]:
y_pred_xtrain = classifierr.predict(x_train)

In [30]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred_xtrain)
print(cm)

[[65  0  0  0  1]
 [ 0 18  0  0  0]
 [ 0  1 14  0  0]
 [ 0  0  0 13  0]
 [ 1  0  0  0 37]]


In [31]:
# 0 = drugY
# 1 = drugA
# 2 = drugB
# 3 = drugC
# 4 = drugX

In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [39]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

dtc_test = dtc.predict(x_test)

In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, dtc_test)
print(cm)

[[25  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  3  0]
 [ 0  0  0  0 16]]


In [41]:
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_test, dtc_test))

Accuracy:  1.0
